/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ConditionIconPaths } from "./models/condition-icon-paths";
import { Forecast } from "./models/forecast";
export namespace Components {
    interface CsdemoCondition {
        "condition": number;
        "iconPaths": ConditionIconPaths;
        "noIcon": boolean;
        "noLabel": boolean;
    }
    interface CsdemoDailyForecast {
        "forecasts": Array<Forecast>;
        "iconPaths": ConditionIconPaths;
        "scale": string;
    }
    interface CsdemoTemperature {
        "scale": string;
        "temperature": number;
    }
    interface CsdemoUvIndex {
        "uvIndex": number;
    }
}
declare global {
    interface HTMLCsdemoConditionElement extends Components.CsdemoCondition, HTMLStencilElement {
    }
    var HTMLCsdemoConditionElement: {
        prototype: HTMLCsdemoConditionElement;
        new (): HTMLCsdemoConditionElement;
    };
    interface HTMLCsdemoDailyForecastElement extends Components.CsdemoDailyForecast, HTMLStencilElement {
    }
    var HTMLCsdemoDailyForecastElement: {
        prototype: HTMLCsdemoDailyForecastElement;
        new (): HTMLCsdemoDailyForecastElement;
    };
    interface HTMLCsdemoTemperatureElement extends Components.CsdemoTemperature, HTMLStencilElement {
    }
    var HTMLCsdemoTemperatureElement: {
        prototype: HTMLCsdemoTemperatureElement;
        new (): HTMLCsdemoTemperatureElement;
    };
    interface HTMLCsdemoUvIndexElement extends Components.CsdemoUvIndex, HTMLStencilElement {
    }
    var HTMLCsdemoUvIndexElement: {
        prototype: HTMLCsdemoUvIndexElement;
        new (): HTMLCsdemoUvIndexElement;
    };
    interface HTMLElementTagNameMap {
        "csdemo-condition": HTMLCsdemoConditionElement;
        "csdemo-daily-forecast": HTMLCsdemoDailyForecastElement;
        "csdemo-temperature": HTMLCsdemoTemperatureElement;
        "csdemo-uv-index": HTMLCsdemoUvIndexElement;
    }
}
declare namespace LocalJSX {
    interface CsdemoCondition {
        "condition"?: number;
        "iconPaths"?: ConditionIconPaths;
        "noIcon"?: boolean;
        "noLabel"?: boolean;
    }
    interface CsdemoDailyForecast {
        "forecasts"?: Array<Forecast>;
        "iconPaths"?: ConditionIconPaths;
        "scale"?: string;
    }
    interface CsdemoTemperature {
        "scale"?: string;
        "temperature"?: number;
    }
    interface CsdemoUvIndex {
        "uvIndex"?: number;
    }
    interface IntrinsicElements {
        "csdemo-condition": CsdemoCondition;
        "csdemo-daily-forecast": CsdemoDailyForecast;
        "csdemo-temperature": CsdemoTemperature;
        "csdemo-uv-index": CsdemoUvIndex;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "csdemo-condition": LocalJSX.CsdemoCondition & JSXBase.HTMLAttributes<HTMLCsdemoConditionElement>;
            "csdemo-daily-forecast": LocalJSX.CsdemoDailyForecast & JSXBase.HTMLAttributes<HTMLCsdemoDailyForecastElement>;
            "csdemo-temperature": LocalJSX.CsdemoTemperature & JSXBase.HTMLAttributes<HTMLCsdemoTemperatureElement>;
            "csdemo-uv-index": LocalJSX.CsdemoUvIndex & JSXBase.HTMLAttributes<HTMLCsdemoUvIndexElement>;
        }
    }
}
